// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using youbefit.Models;

namespace youbefit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180702144447_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("youbefit.Models.Blog", b =>
                {
                    b.Property<int>("Blogid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("blogid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Blogid");

                    b.ToTable("blog");
                });

            modelBuilder.Entity("youbefit.Models.Post", b =>
                {
                    b.Property<int>("Postid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("postid");

                    b.Property<int>("Blogid")
                        .HasColumnName("blogid");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Postid");

                    b.HasIndex("Blogid");

                    b.ToTable("post");
                });

            modelBuilder.Entity("youbefit.Models.Post", b =>
                {
                    b.HasOne("youbefit.Models.Blog", "Blog")
                        .WithMany("Post")
                        .HasForeignKey("Blogid")
                        .HasConstraintName("fk_post_blog_blogid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
